import * as anchor from '@coral-xyz/anchor';
import { Connection, PublicKey, Transaction } from '@solana/web3.js';
import { Currency, TaskMode } from '../domain';
// import { Basira } from './idl/basira'; // Generated by `anchor build` into program/target/types/

// NOTE: this program ID is the Anchor scaffold default. After running
// `anchor keys sync` the real ID gets written into program/Anchor.toml and
// program/programs/basira/src/lib.rs. Update this string to match.
export const PROGRAM_ID = new PublicKey('Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS');

// All builders below are stubs. They preserve the call signatures used by
// callers in shared/services/* and worker/cron/* so the rest of the project
// can be wired up. Real bodies need the IDL emitted by `anchor build`.

export async function buildCreateTaskTransaction(
  _connection: Connection,
  _posterWallet: PublicKey,
  _taskIdBytes: number[],
  _mode: TaskMode,
  _assignedAgent: PublicKey | null,
  _currency: Currency,
  _amount: anchor.BN,
  _deadline: anchor.BN,
  _criteriaHash: number[],
): Promise<Transaction> {
  return new Transaction();
}

export async function buildAssignAgentTransaction(
  _connection: Connection,
  _posterWallet: PublicKey,
  _taskIdBytes: number[],
  _assignedAgent: PublicKey,
): Promise<Transaction> {
  return new Transaction();
}

// Additional builders to add as the program is wired up:
// buildSubmitDeliverableTransaction, buildApproveTransaction,
// buildClaimAfterTimeoutTransaction, buildOpenDisputeTransaction,
// buildResolveDisputeTransaction, buildExpireTaskTransaction,
// buildCancelTaskTransaction, buildRegisterAgentTransaction.
